spring.application.name=Event
server.port=${PORT:8080}
spring.data.mongodb.uri=mongodb+srv://msivasankari1708_db_user:A0OJlZ30yzb43qEF@eventregisteration.lgrhy2j.mongodb.net/EventRegisteration?appName=EventRegisteration

