spring.application.name=Event
server.port=${PORT:8080}
spring.data.mongodb.uri=spring.data.mongodb.uri=mongodb+srv://msivasankari1708_db_user:A0OJlZ30yzb43qEF@eventregistration.lgrhy2j.mongodb.net/EventRegistration?retryWrites=true&w=majority